2025-04-26 19:23:00,959 - root - ERROR - [routes.py:269] - Error processing CSV file: no such column: bpd.timestamp
Traceback (most recent call last):
  File "/home/thecoderbee/Desktop/calibration_curve_testing/src/api/routes.py", line 236, in index
    all_predictions = get_all_predictions(100)
  File "/home/thecoderbee/Desktop/calibration_curve_testing/src/utils/db.py", line 171, in get_all_predictions
    batch_predictions = conn.execute(
sqlite3.OperationalError: no such column: bpd.timestamp
